# List of 300 advanced Google dorks for bug bounty hunting
google_dorks = [
    "site:example.com inurl:admin",
    "site:example.com intitle:index of",
    "site:example.com filetype:pdf",
    "site:example.com inurl:login",
    "site:example.com inurl:register",
    "site:example.com intitle:login",
    "site:example.com inurl:admin/config",
    "site:example.com inurl:dashboard",
    "site:example.com inurl:wp-content",
    "site:example.com intitle:index.of .git",
    "site:example.com filetype:xml",
    "site:example.com intitle:admin",
    "site:example.com inurl:wp-admin",
    "site:example.com inurl:phpmyadmin",
    "site:example.com intitle:configuration",
    "site:example.com inurl:upload",
    "site:example.com intitle:password",
    "site:example.com inurl:api",
    "site:example.com inurl:login.php",
    "site:example.com inurl:reset-password",
    "site:example.com inurl:forgot-password",
    "site:example.com inurl:change-password",
    "site:example.com inurl:user",
    "site:example.com inurl:admin-panel",
    "site:example.com inurl:panel",
    "site:example.com inurl:secure",
    "site:example.com inurl:config.php",
    "site:example.com inurl:index.php",
    "site:example.com inurl:setup",
    "site:example.com intitle:admin login",
    "site:example.com inurl:manager",
    "site:example.com inurl:/admin/",
    "site:example.com inurl:wp-login",
    "site:example.com intitle:index of /uploads",
    "site:example.com filetype:sql",
    "site:example.com inurl:backup",
    "site:example.com intitle:\"index of\" .env",
    "site:example.com inurl:/.git",
    "site:example.com inurl:/uploads/",
    "site:example.com inurl:/wp-content/uploads",
    "site:example.com intitle:index of /wp-includes",
    "site:example.com filetype:log",
    "site:example.com inurl:git-config",
    "site:example.com intitle:debug",
    "site:example.com inurl:debug",
    "site:example.com inurl:phpinfo.php",
    "site:example.com inurl:debug.log",
    "site:example.com inurl:configuration.php",
    "site:example.com intitle:index of /admin",
    "site:example.com inurl:/wp-includes/js/",
    "site:example.com inurl:robots.txt",
    "site:example.com intitle:index of /config",
    "site:example.com inurl:.git",
    "site:example.com inurl:/config/",
    "site:example.com filetype:db",
    "site:example.com intitle:index of /admin/",
    "site:example.com inurl:login.aspx",
    "site:example.com inurl:admin.asmx",
    "site:example.com inurl:admin-config",
    "site:example.com inurl:admin/dash",
    "site:example.com inurl:admin_control",
    "site:example.com inurl:manage",
    "site:example.com inurl:upload.php",
    "site:example.com intitle:index of /logs",
    "site:example.com filetype:conf",
    "site:example.com inurl:index.html",
    "site:example.com inurl:.bash_history",
    "site:example.com inurl:.env",
    "site:example.com inurl:.gitignore",
    "site:example.com filetype:json",
    "site:example.com inurl:remote-config",
    "site:example.com inurl:.gitmodules",
    "site:example.com filetype:log",
    "site:example.com inurl:admin-dashboard",
    "site:example.com inurl:wp-admin/admin.php",
    "site:example.com inurl:.htaccess",
    "site:example.com inurl:debug-backtrace",
    "site:example.com intitle:\"index of\" /uploads",
    "site:example.com inurl:admin-area",
    "site:example.com filetype:json",
    "site:example.com inurl:admin.php",
    "site:example.com inurl:rest-api",
    "site:example.com filetype:json",
    "site:example.com inurl:login.php",
    "site:example.com filetype:bak",
    "site:example.com intitle:index of .git",
    "site:example.com intitle:index of config",
    "site:example.com inurl:index.js",
    "site:example.com inurl:checkout",
    "site:example.com filetype:env",
    "site:example.com inurl:.bash_history",
    "site:example.com filetype:backup",
    "site:example.com inurl:openapi",
    "site:example.com filetype:bak",
    "site:example.com inurl:/admin_files/",
    "site:example.com inurl:upload",
    "site:example.com filetype:yaml",
    "site:example.com inurl:session_id",
    "site:example.com inurl:redis",
    "site:example.com inurl:phpinfo",
    "site:example.com filetype:dump",
    "site:example.com inurl:admin-console",
    "site:example.com intitle:index of /config.php",
    "site:example.com inurl:admin/configure",
    "site:example.com inurl:settings.php",
    "site:example.com inurl:loginform",
    "site:example.com inurl:reset-form",
    "site:example.com inurl:loginpanel",
    "site:example.com intitle:dashboard",
    "site:example.com inurl:authentication",
    "site:example.com inurl:logs/",
    "site:example.com inurl:public/",
    "site:example.com inurl:mail.php",
    "site:example.com inurl:/assets/js/",
    "site:example.com filetype:inc",
    "site:example.com inurl:.zip",
    "site:example.com inurl:/wp-content/plugins/",
    "site:example.com inurl:login.html",
    "site:example.com inurl:admin/resources",
    "site:example.com inurl:access-log",
    "site:example.com inurl:session_id",
    "site:example.com inurl:backup.zip",
    "site:example.com inurl:session-log",
    "site:example.com intitle:index of /private/",
    "site:example.com filetype:js",
    "site:example.com inurl:authentication-token",
    "site:example.com inurl:dashboard-settings",
    "site:example.com inurl:admin/settings",
    "site:example.com inurl:.git",
    "site:example.com intitle:\"index of\" /admin",
    "site:example.com filetype:env",
    "site:example.com inurl:.gitattributes",
    "site:example.com inurl:.bashrc",
    "site:example.com inurl:/admin/",
    "site:example.com inurl:admin-logs",
    "site:example.com intitle:debugging",
    "site:example.com inurl:index.yaml",
    "site:example.com intitle:site-map",
    "site:example.com inurl:password-file",
    "site:example.com intitle:index of /private",
    "site:example.com inurl:admin/config",
    "site:example.com inurl:admin/login",
    "site:example.com inurl:admin/panel",
    "site:example.com inurl:admin/dashboard",
    "site:example.com inurl:admin/settings",
    "site:example.com inurl:admin/upload",
    "site:example.com inurl:admin/backup",
    "site:example.com inurl:admin/debug",
    "site:example.com inurl:admin/phpinfo",
    "site:example.com inurl:admin/logs",
    "site:example.com inurl:admin/config.php",
    "site:example.com inurl:admin/index.php",
    "site:example.com inurl:admin/setup",
    "site:example.com inurl:admin/manager",
]

# Ask the user for the target domain to replace "example.com"
target_domain = input("Enter the target domain to replace (e.g., targetdomain.com): ")

# Replace the domain in each dork
modified_dorks = [dork.replace("example.com", target_domain) for dork in google_dorks]

# Save the modified dorks to a .txt file
with open("modified_dorks.txt", "w") as f:
    for dork in modified_dorks:
        f.write(dork + "\n")

print("Modified Google dorks saved to modified_dorks.txt")
